services:
  izyplace:
    image: izyplace:latest
    networks:
      - docker_network
    ports:
      - "8000:8000"
  mongo:
    image: mongodb/mongodb-community-server:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    expose:
      - 27017
    ports:
      - "27017:27017"
networks:
  docker_network:
    driver: bridge
